### ISSUE TITLE
Support for Oracle Linux 8

### ISSUE THREAD

**Issue by gdelisle** [CU-CommunityApps/ct-patching-scanning#4]
I have written support for Oracle Linux 8 into our fork of this project: https://github.com/cul-it/ct-patching-scanning 
Salient differences are in the last commit: https://github.com/cul-it/ct-patching-scanning/commit/d5beeef3622751bfe5ddc4dc4b96cd0308cbf851
The changes involve 1) adding a PatchBaseLine for Oracle Linux, which is now an option within SSM Inspector. This should be forward-compatible with future OL versions. 2) adjusting the PatchAndRemoveKernelsSSMDoc script, which breaks with OS versions > 7 because of breaking changes with the package-cleanup tool. To get around this, I added a conditional to detect the presence of dnf and remove old kernels with that tool instead. The command to remove old kernels with dnf is `dnf remove --oldinstallonly --setopt installonly_limit=2`. If dnf is not detected, it's assumed that the OS is RHEL-based >= 7 and the package-cleanup command is used as before.
This patch is not tested with OL > 8 but it is installed in our environment, it is working on our OL 8 machines and it is not disrupting our CentOS 7 or Amazon Linux 2 patching. Feedback is appreciated.

**Comment by paul-e-allen** [comment]
Thank you @gdelisle!
